version: '3.7'

services:
  database:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shoper
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '13306:3306'

volumes:
  mysql_data:
